### ISSUE TITLE
Improve variable naming

### ISSUE THREAD

**Issue by Leobouloc** [openfun/open-badges-client#29]
### 1

https://github.com/openfun/open-badges-client/blob/cda7350258247e3addd2fdeb2cad0fa44e5e6a07/src/obc/providers/obf.py

The use of the word "issue" in variable naming is not ideal in class names such as `BadgeIssue` (would be interpreted as "problem with the badge"), `IssueQuery` (interpreted as "query for a problem" or alternatevely "issue a query" which is verb and not appropriate class naming). 

The word "issue" should likely be replaced by "issuing" (or ideally a less confusing term), for example in the docstring `"""Open Badge Factory badge issue Model."""

### 2

`BadgeRevokation` should be `BadgeRevocation`

### TODO

- [ ] Fix 1
- [x] Fix 2

**Comment by wilbrdt** [comment]
The word "event" is used instead of "issue" in the OBF API, and could be a replacement indeed!
